<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Listagem.aspx.cs" Inherits="Cadastro_Jogador.Listagem" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>

            <asp:Literal ID="LtrLista" runat="server" Text="Jogadores Cadastrados"></asp:Literal>
            <asp:GridView ID="GridViewJogadores" runat="server" autogeneratecolumns="true" AutoGenerateDeleteButton="true"  AutoGenerateEditButton="true" OnRowEditing="AtualizarCadastro" allowpaging="true">
                <columns>
                 <asp:TemplateField HeaderText="Acesso aos Documentos">
                     <itemtemplate>
                        <asp:Button ID="BttSelec" runat="server" Text="Documentos" Width="160" />
                    </itemtemplate>
                </asp:TemplateField>
                </columns>
            </asp:GridView>
           

        </div>
    </form>
</body>
</html>
